### PR TITLE
⚠️ assigned but unused variable - patch

### PR DESCRIPTION
**Pull request by amatsuda**
Here's a trivial fix for a ⚠️.

### CODE REVIEW

**Comment by apotonick** [comment]
@amatsuda Akiiiiirraaaaaaa !!!!! 😍

**Comment by apotonick** [comment]
Do we actually use `Version` anywhere? I was about to remove it from the gem at some point in favor of `Gem`'s methods. So, `_` does the trick?

**Comment by amatsuda** [comment]
I saw this warning in our legacy app (that I just started working on today) still bundles cells 3.
According to the stacktrace,this method was called via https://github.com/apotonick/cells/blob/v3.11.3/lib/cell/rails/view_model.rb#L153.

If you're sure that this was the only usage, maybe you can remove it.

**Comment by apotonick** [comment]
Need help upgrading?

**Comment by amatsuda** [comment]
Haha, thanks! Maybe I'll ask you if I get stuck. :stuck_out_tongue_closed_eyes:

**Comment by apotonick** [comment]
I removed `Uber::Version` from 0.1.0. :heart:

**Comment by amatsuda** [comment]
🤘

**Pull request closed without merging**
